### ISSUE TITLE
THIS IS NOT AN ISSUE THIS IS JUST A THANKFUL MESSAGE

### ISSUE THREAD

**Issue by Anoirwork** [H29A/lenovo-ideapad-gaming-3-hackintosh#2]
Hi man,
Dude you did a great job posting this EFI on github i had saved me days of head achs and anxiousness i thought i won't achieve   hackintoshing my laptop which i had bought for this purpose.
Thank you so much for the EFI you put and the work you had done . i wish you all the best.
i will put my specs here maybe one day someone like me would need such EFI : 
MSI GP66 leopard 10UE 
i7 10870H
UHD 630
chipset Intel HM470
16 GB
2 TB
RTX 3070 (disabled)

**Comment by H29A** [comment]
No problem, thanks inspire me to help the community :)
I have an opencore build for i9-12900k with DDR5 RAM, maybe later I'll get around to creating a repository!
